#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

OUTPUT_ROOT="${PROJECT_ROOT}/build/hyde-live-smoke"
USE_EXISTING_GTK=0
KEEP_GENERATED_GTK=0
GENERATED_GTK=0

usage() {
  cat <<'USAGE'
Usage: tools/prepare-hyde-live-smoke.sh [options]

Prepare a development-only HyDE import tree for live testing the Witcher3
runtime before the custom Witcher3-HyDE icon artwork/package is complete.

The repository itself is not modified. The staged hypr.theme omits only the
$ICON_THEME declaration so current HyDE can keep/use its available icon theme
instead of requiring the unfinished Icon_Witcher3-HyDE archive.

Options:
  --use-existing-gtk   Use an already-built Source/arcs/Gtk_Witcher3.tar.xz.
                       Fail if it is missing instead of rebuilding it.
  --keep-generated-gtk Keep a GTK archive generated by this invocation under
                       Source/arcs/ after the smoke tree has been prepared.
  --output DIR         Write the smoke-test tree to DIR instead of
                       build/hyde-live-smoke.
  -h, --help           Show this help.

This script only PREPARES the tree. It does not install or switch the live
HyDE theme. After reviewing the staged tree, run the printed theme.patch.sh
command explicitly on the HyDE machine.
USAGE
}

while (($#)); do
  case "$1" in
    --use-existing-gtk)
      USE_EXISTING_GTK=1
      shift
      ;;
    --keep-generated-gtk)
      KEEP_GENERATED_GTK=1
      shift
      ;;
    --output)
      [[ $# -ge 2 ]] || { echo "error: --output requires a directory" >&2; exit 2; }
      OUTPUT_ROOT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'error: unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    printf 'error: required command not found: %s\n' "$command_name" >&2
    exit 1
  fi
}

for command_name in awk cp find grep python3 sha256sum tar; do
  require_command "$command_name"
done

THEME_DIR="${PROJECT_ROOT}/Configs/.config/hyde/themes/Witcher3"
HYPR_THEME="${THEME_DIR}/hypr.theme"
GTK_ARCHIVE="${PROJECT_ROOT}/Source/arcs/Gtk_Witcher3.tar.xz"
GTK_BUILD="${PROJECT_ROOT}/tools/build-gtk.sh"

[[ -d "$THEME_DIR" ]] || { printf 'error: Witcher3 theme directory missing: %s\n' "$THEME_DIR" >&2; exit 1; }
[[ -f "$HYPR_THEME" ]] || { printf 'error: hypr.theme missing: %s\n' "$HYPR_THEME" >&2; exit 1; }
[[ -x "$GTK_BUILD" ]] || { printf 'error: GTK builder is not executable: %s\n' "$GTK_BUILD" >&2; exit 1; }

if ! grep -Eq '^[[:space:]]*\$GTK_THEME[[:space:]]*=[[:space:]]*Witcher3[[:space:]]*$' "$HYPR_THEME"; then
  echo 'error: repository hypr.theme must declare $GTK_THEME = Witcher3' >&2
  exit 1
fi

if ! grep -Eq '^[[:space:]]*\$ICON_THEME[[:space:]]*=[[:space:]]*Witcher3-HyDE[[:space:]]*$' "$HYPR_THEME"; then
  echo 'error: repository hypr.theme must declare $ICON_THEME = Witcher3-HyDE' >&2
  exit 1
fi

if grep -Eq '^[[:space:]]*\$CURSOR_(THEME|SIZE)[[:space:]]*=' "$HYPR_THEME"; then
  echo 'error: repository hypr.theme violates the v1 cursor inheritance policy' >&2
  exit 1
fi

wallpaper_count="$(find "$THEME_DIR/wallpapers" -maxdepth 1 -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.gif' \) | wc -l | tr -d ' ')"
if [[ "$wallpaper_count" -lt 1 ]]; then
  echo 'error: Witcher3 smoke tree requires at least one real wallpaper' >&2
  exit 1
fi

cleanup_generated_gtk() {
  if ((GENERATED_GTK)) && ((!KEEP_GENERATED_GTK)); then
    rm -f "$GTK_ARCHIVE"
    rmdir "${PROJECT_ROOT}/Source/arcs" 2>/dev/null || true
    rmdir "${PROJECT_ROOT}/Source" 2>/dev/null || true
  fi
}
trap cleanup_generated_gtk EXIT

if ((USE_EXISTING_GTK)); then
  [[ -f "$GTK_ARCHIVE" ]] || {
    printf 'error: --use-existing-gtk requested but archive is missing: %s\n' "$GTK_ARCHIVE" >&2
    exit 1
  }
else
  if [[ ! -f "$GTK_ARCHIVE" ]]; then
    GENERATED_GTK=1
  fi
  "$GTK_BUILD" --package
fi

[[ -f "$GTK_ARCHIVE" ]] || { printf 'error: GTK archive missing after build: %s\n' "$GTK_ARCHIVE" >&2; exit 1; }

top_entries="$(tar -tJf "$GTK_ARCHIVE" | sed 's#^\./##' | cut -d/ -f1 | sort -u)"
if [[ "$top_entries" != 'Witcher3' ]]; then
  printf 'error: GTK archive must contain exactly one top-level Witcher3 directory; got:\n%s\n' "$top_entries" >&2
  exit 1
fi

GTK_SHA256="$(sha256sum "$GTK_ARCHIVE" | awk '{print $1}')"

rm -rf "$OUTPUT_ROOT"
mkdir -p "$OUTPUT_ROOT/Source/arcs"
cp -a "${PROJECT_ROOT}/Configs" "$OUTPUT_ROOT/Configs"
cp -a "$GTK_ARCHIVE" "$OUTPUT_ROOT/Source/arcs/Gtk_Witcher3.tar.xz"

STAGED_HYPR="${OUTPUT_ROOT}/Configs/.config/hyde/themes/Witcher3/hypr.theme"

python3 - "$STAGED_HYPR" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
pattern = re.compile(r"^[ \t]*\$ICON_THEME[ \t]*=[ \t]*Witcher3-HyDE[ \t]*\r?\n?", re.MULTILINE)
matches = pattern.findall(text)
if len(matches) != 1:
    raise SystemExit(f"expected exactly one Witcher3-HyDE ICON_THEME declaration, found {len(matches)}")
text = pattern.sub("", text, count=1)
path.write_text(text, encoding="utf-8")
PY

if grep -Eq '^[[:space:]]*\$ICON_THEME[[:space:]]*=' "$STAGED_HYPR"; then
  echo 'error: development smoke hypr.theme still declares an icon theme' >&2
  exit 1
fi

if ! grep -Eq '^[[:space:]]*\$GTK_THEME[[:space:]]*=[[:space:]]*Witcher3[[:space:]]*$' "$STAGED_HYPR"; then
  echo 'error: development smoke hypr.theme lost the Witcher3 GTK declaration' >&2
  exit 1
fi

if find "$OUTPUT_ROOT" -type f -name 'Icon_*.tar.*' -print -quit | grep -q .; then
  echo 'error: development smoke tree must not contain an icon archive' >&2
  exit 1
fi

if find "$OUTPUT_ROOT" -type f -name 'Cursor_*.tar.*' -print -quit | grep -q .; then
  echo 'error: development smoke tree must not contain a cursor archive' >&2
  exit 1
fi

REPO_COMMIT="unknown"
if command -v git >/dev/null 2>&1 && git -C "$PROJECT_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  REPO_COMMIT="$(git -C "$PROJECT_ROOT" rev-parse HEAD)"
fi

cat >"$OUTPUT_ROOT/DEV_SMOKE_TEST.txt" <<EOF
Witcher3 HyDE development smoke-test tree

Repository commit: ${REPO_COMMIT}
GTK archive SHA-256: ${GTK_SHA256}
Wallpaper count: ${wallpaper_count}

Intentional development-only difference from the repository:
- \$ICON_THEME = Witcher3-HyDE is removed from the STAGED hypr.theme only.
- No Icon_*.tar.* package is supplied because original Witcher3-HyDE artwork is not complete.
- No cursor package or cursor override is supplied, matching the v1 cursor policy.

The repository hypr.theme is unchanged.
Do not publish this staging tree as a release package.
EOF

PATCHER="${HOME}/.local/lib/hyde/theme.patch.sh"

printf '\nWitcher3 HyDE development smoke tree prepared successfully.\n'
printf 'stage: %s\n' "$OUTPUT_ROOT"
printf 'GTK SHA-256: %s\n' "$GTK_SHA256"
printf 'wallpapers: %s\n' "$wallpaper_count"
printf 'repository hypr.theme: unchanged\n'
printf 'staged icon override: omitted intentionally\n\n'
printf 'Review first:\n  %s\n\n' "$OUTPUT_ROOT/DEV_SMOKE_TEST.txt"
printf 'Then, on the HyDE machine, explicitly run:\n  %q Witcher3 %q\n' "$PATCHER" "$OUTPUT_ROOT"
